### ISSUE TITLE
ummm

### ISSUE THREAD

**Issue by jimoquinn** [JoeSubbi/Sea_of_Thieves#1]
Bruh...

https://www.virustotal.com/gui/file/4b2b8a848cd0f7b31b1e247bc2914c1255371f67a03155133a7de5034c3d4905?nocache=1

![sot-route-planner](https://user-images.githubusercontent.com/1494571/136119842-0e57771b-77fd-4bad-a242-d4f7a441a1c2.png)

**Comment by JoeSubbi** [comment]
I have no clue why that is coming up, feel free to look at the code, there isn't anything malicious. If it was a virus I wouldn't be publishing the source code

Feel free to delete the .exe and compile it yourself. I used py2exe

The instructions are in `install w icon.txt`

It is also worth noting you can just run `route_planner.py`
Compilation was just to make a nice easy executable
